aukletio/Auklet-Agent-Java

- .circleci/config.yml
- .devops/deploy.sh
- .devops/prep-for-whitesource.sh
- LICENSE
- build.gradle
- src/main/java/io/auklet/agent/Auklet.java
- src/main/java/io/auklet/agent/Device.java
- src/main/java/io/auklet/agent/MQTT.java
- All pushes to the 3 main branches will result in published artifacts being pushed to Bintray.
- Added WhiteSource scanning (skipped for PR builds).
- Parameterized the Auklet base URL via the env var `AUKLET_BASEURL`.
- Added CircleCI dependency caching.
- Added Apache 2.0 license.
> APM-1632: Add Bintray deployment (and other devops changes)

- .circleci/config.yml
- .devops/duplicateBuildCheck.sh
- .devops/flagBuilds.sh
- .devops/prep-for-whitesource.sh
CircleCI is now building `origin` branch pushes twice - once for being an `origin` branch and again for being the `HEAD` of an open PR. This should only happen in theory to the `master` branch because it is the default branch, but I've already seen it happen with the `rc` branch.
Aside from the above-mentioned `rc` double-build issue, which I believe is a bug, this behavior is by design and it messes with our deploy processes. This PR fixes this by checking for/aborting redundant builds.
> Add duplicate build check

- README.md
- src/main/java/io/auklet/agent/Auklet.java
- src/main/java/io/auklet/agent/AukletExceptionHandler.java
- src/main/java/io/auklet/agent/Device.java
- src/main/java/io/auklet/agent/MQTT.java
- src/main/java/io/auklet/agent/Util.java
This PR tries to add more robust error handling in java agent. 
If any of the following fails we do not set the unhandled exception handler 
- We can't get the CA cert 
- Can't register a device
- Could not connect to MQTT client
> Add more error handling

- src/main/java/io/auklet/agent/Auklet.java
- src/main/java/io/auklet/agent/AukletExceptionHandler.java
This PR does the following:
This functionality is solely up to the end user to decide which handled exceptions he/she want to get notified for when they occur.
> APM-1645: Add custom logging of handled exception events 

- README.md
- src/main/java/io/auklet/agent/Auklet.java
- src/main/java/io/auklet/agent/Device.java
- src/main/java/io/auklet/agent/Util.java
- Support for adding arbitrary dir for config files for server type applications. 
- It can be set at runtime using `java -Dauklet.config.dir="custom/file/path/dir" MyApp`
- Additional: 
- Revert `clientPassword` and `clientId` names to `client_password` and `client_id` respectively since the jsonObject returned by the backend contrains the fields in the later format
> support for an arbitrary dir for config files

- src/main/java/io/auklet/agent/DataRetention.java
- src/main/java/io/auklet/agent/broker/MQTTClient.java
- Update the amount of data sent immediately after the client publishes it to mqtt
- This PR makes the `checkDate` timer thread daemon so the agent does not hang after the application exits
> APM-1697: Fix Mqtt publish error and agent hung problem

- src/main/java/io/auklet/config/DataUsageTracker.java
- src/main/java/io/auklet/sink/AukletIoSink.java
- Formatting of long literal in DataUsageTracker.
- Wait for MQTT connect to succeed before considering sink as started; fail if connect takes more than 10 seconds.
> Miscellaneous bugfixes

- build.gradle
This PR removes the shadow JAR plugin since it is no longer needed. We will not distribute the Auklet agent as a fat JAR, and testing the agent locally with the fat JAR leads to inconsistencies in test results.
> Remove shadow JAR plugin

- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/core/AukletApi.java
- src/main/java/io/auklet/sink/AukletIoSink.java
- src/main/java/io/auklet/sink/Sink.java
This PR makes the init/shutdown methods more defensive:
- Catch `Exception` during `init` instead of `AukletException` to protect against programming errors at runtime, and to ensure that the agent always shuts down cleanly if it fails to init.
- Make `shutdown` methods more defensive (assuming `null` class members) so that they will properly no-op if asked to shutdown due to a bad init.
> Make init/shutdown more defensive

- src/main/java/io/auklet/platform/JavaPlatform.java
- src/main/java/io/auklet/platform/metrics/OSMX.java
In Java 8 Compact Profiles 1/2, and in certain Java 9+ environments, the `java.lang.management` classes are not available. This PR adds support for these scenarios by allowing these classes not to exist, and returning relevant no-op values for the affected methods.
> Make JMI class requirement optional

- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/config/DataUsageTracker.java
- src/main/java/io/auklet/misc/AukletDaemonExecutor.java
Some daemon tasks, like `DataUsageTracker`'s task to write data to disk, should not be logged by `AukletDaemonExecutor` if they are cancelled because cancelling the task is part of the happy-path logic. This PR adds `CancelSilentlyFutureTask` (which is `Runnable` and thus passable to `Auklet.scheduleOneShotTask`) which is honored by `AukletDaemonExecutor` to skip logging of cancelled tasks.
> Allow some tasks to be cancelled without logging

- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/misc/AukletDaemonExecutor.java
- src/main/java/io/auklet/sink/AukletIoSink.java
This is a workaround for https://github.com/aukletio/Auklet-Agent-Java/pull/57.
Changes:
- MQTT disconnect exception is not logged.
- `CancellationException`s are not logged while the agent is shutting down. Sometimes MQTT disconnect causes these exceptions if their corresponding thread tasks do not complete before the JVM begins to shutdown. In general, it's good not to log _any_ `CancellationException`s during agent shutdown (because it makes sense for tasks to be cancelled during that timeframe), so this change will _not_ be reverted when https://github.com/aukletio/Auklet-Agent-Java/pull/57 is merged, and thus this PR is labeled as an enhancement.
> Hide MQTT disconnect errors

- src/main/java/io/auklet/platform/AndroidPlatform.java
- src/main/java/io/auklet/platform/JavaPlatform.java
This PR renames the `aukletFiles` dir to `.auklet` so that the config dir is hidden by default.
> Rename config dir to .auklet

- build.gradle
- src/main/java/io/auklet/Auklet.java
Not sure when this broke (or if it ever worked), but the agent version has not been retrieved correctly from the JAR manifest's `Implementation-Version` attribute. This approach, even when fixed for Java SE, would not work for Android.
This PR adds a Gradle plugin that generates a `BuildConfig` Java class during the build with our version number, which we then reference at runtime to get the agent version. This fixes both Java SE and Android.
> Fix retrieval of agent version

- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/config/AbstractConfigFile.java
- src/main/java/io/auklet/config/AbstractJsonConfigFileFromApi.java
- src/main/java/io/auklet/config/AukletIoBrokers.java
- src/main/java/io/auklet/config/AukletIoCert.java
- src/main/java/io/auklet/config/DataUsageLimit.java
- src/main/java/io/auklet/config/DataUsageTracker.java
- src/main/java/io/auklet/config/DeviceAuth.java
- src/main/java/io/auklet/core/AukletApi.java
- src/main/java/io/auklet/core/AukletExceptionHandler.java
- src/main/java/io/auklet/core/DataUsageMonitor.java
- src/main/java/io/auklet/misc/AukletDaemonExecutor.java
- src/main/java/io/auklet/misc/PahoLogger.java
- src/main/java/io/auklet/misc/Util.java
- src/main/java/io/auklet/platform/AbstractPlatform.java
- src/main/java/io/auklet/platform/AndroidPlatform.java
- src/main/java/io/auklet/platform/JavaPlatform.java
- src/main/java/io/auklet/platform/Platform.java
- src/main/java/io/auklet/platform/metrics/AndroidMetrics.java
- src/main/java/io/auklet/sink/AbstractSink.java
- src/main/java/io/auklet/sink/SerialPortSink.java
- Cleanup Javadocs, documentation of thread safety/nullable handling, and code style/formatting.
- Change how some exceptions were being propagated internally.
- Fix thread safety for `DataUsageTracker` and `AndroidMetrics`.
- Cause agent init to fail on Android if API level is less than 16.
- Fix memory usage retrieval in `AndroidMetrics`.
> Miscellaneous fixes/cleanup

- .circleci/config.yml
- README.md
- build.gradle
- settings.gradle
- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/misc/AukletDaemonExecutor.java
- Switch build config plugins so we can compile with Gradle 4/Java 7
- Add support for fixing cross-compilation warnings when using Java 8
- Fix all other fixable Gradle warnings
- Use Java 11 in CI
- Update README
> Support Java 7 more strictly

- src/main/java/io/auklet/misc/Tls12SocketFactory.java
- src/main/java/io/auklet/platform/AndroidPlatform.java
- src/main/java/io/auklet/sink/AukletIoSink.java
MQTT was broken on Android API level 16 because TLSv1.2 is not enabled by default for SSL sockets in that version of Android. Our connection to the Auklet API is not impacted by this because OkHttp handles this problem transparently.
This PR adds a socket factory for MQTT that only returns TLSv1.2-enabled sockets, and logs a warning for the affected API levels in case this workaround somehow doesn't work on particular devices. (Other than the end user updating the Android security provider via Google Play Services, this PR is the only workaround we can make.)
> Fix TLS 1.2 on Android API levels 16 thru 19

- src/main/java/io/auklet/misc/Tls12SocketFactory.java
If `Tls12SocketFactory` is instantiated with a `null` context, the default context being used was protocol `TLS`, not `TLSv1.2`. This PR fixes that discrepancy and also does minor style cleanup of the class.
> Make default SSL context use TLS 1.2

- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/config/AbstractJsonConfigFileFromApi.java
- src/main/java/io/auklet/config/AukletIoBrokers.java
- src/main/java/io/auklet/config/AukletIoCert.java
- src/main/java/io/auklet/config/DataUsageLimit.java
- src/main/java/io/auklet/config/DeviceAuth.java
- src/main/java/io/auklet/net/Https.java
- src/main/java/io/auklet/util/Util.java
This PR adds better handling of requests to the Auklet API by ensuring that any usage of the API key is tied exclusively to requests that only use the base URL. This ensure that API keys will only ever be sent to A. `api.auklet.io`, or B. whatever value the end user has configured for the base URL, in which case the security of their API key becomes their responsibility.
> Improve Auklet API credential security

- README.md
- src/main/java/io/auklet/Auklet.java
- src/main/java/io/auklet/Config.java
- src/main/java/io/auklet/config/AbstractConfigFileFromApi.java
- src/main/java/io/auklet/config/DataUsageTracker.java
- src/main/java/io/auklet/config/DeviceAuth.java
- src/main/java/io/auklet/misc/OSMX.java
- src/main/java/io/auklet/platform/AbstractPlatform.java
- src/main/java/io/auklet/platform/JavaPlatform.java
- src/main/java/io/auklet/util/FileUtil.java
- src/main/java/io/auklet/util/SysUtil.java
- src/main/java/io/auklet/util/ThreadUtil.java
This PR documents the permissions that the Auklet agent (and its dependencies) require in order to function, along with additional optional/recommended permissions depending on what features the end user may be using.
To ensure that logging is kept to a minimum, and also because end users could forego envvar/sysprop configuration entirely and thus do not need to see these warnings, logging of warnings when Auklet config envvars/sysprops are forbidden by the JVM security manager are suppressed by default, and can be re-enabled by the envvar/sysprop `AUKLET_LOUD_SECURITY_EXCEPTIONS/auklet.loud.security.exceptions`, which themselves require their own permissions (and thus are documented in this PR).
> Document required permissions / allow silencing of missing permission warnings

- src/main/java/io/auklet/Auklet.java
1. If loud logging of security exceptions was disabled, a warning would be logged if _either_ the JVM sysprop _or_ the envvar that controls this feature could not be checked. This is a bug; now, the warning is logged only if _both_ the JVM sysprop _and_ the envvar could not be checked.
2. A subtle bug regarding explicit shutdown and JVM shutdown hooks was fixed:
- In policy-controlled JVM environments, it is possible that the `java.lang.RuntimePermission "shutdownHooks"` is not granted. In such scenarios, if the agent is configured to install a JVM shutdown hook, an exception will occur *on startup* and the agent will fail to initialize. This is intended behavior.
- When the agent is shut down, the agent currently attempts to remove its JVM shutdown hook if either of the following is …
> Minor bug fixes
